sfr05_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sfr05_joint
    joint_speed: 0.10
    motor:
        id: 5
        init: 512
        min: 316
        max: 708

sfr04_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sfr04_joint
    joint_speed: 0.10
    motor:
        id: 4
        init: 512
        min: 316
        max: 708

sfr03_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sfr03_joint
    joint_speed: 0.10
    motor:
        id: 3
        init: 512
        min: 316
        max: 708        

sfl02_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sfl02_joint
    joint_speed: 0.10
    motor:
        id: 2
        init: 512
        min: 316
        max: 708

sfl01_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sfl01_joint
    joint_speed: 0.10
    motor:
        id: 1
        init: 512
        min: 316
        max: 708

sfl00_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sfl00_joint
    joint_speed: 0.10
    motor:
        id: 0
        init: 512
        min: 316
        max: 708  


sbr11_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sbr11_joint
    joint_speed: 0.10
    motor:
        id: 11
        init: 512
        min: 316
        max: 708

sbr10_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sbr10_joint
    joint_speed: 0.10
    motor:
        id: 10
        init: 512
        min: 316
        max: 708

sbr09_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sbr09_joint
    joint_speed: 0.10
    motor:
        id: 9
        init: 512
        min: 316
        max: 708        

sbl08_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sbl08_joint
    joint_speed: 0.10
    motor:
        id: 8
        init: 512
        min: 316
        max: 708

sbl07_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sbl07_joint
    joint_speed: 0.10
    motor:
        id: 7
        init: 512
        min: 316
        max: 708

sbl06_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sbl07_joint
    joint_speed: 0.10
    motor:
        id: 6
        init: 512
        min: 316
        max: 708  