sfr05_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sfr05_joint
    joint_speed: 1.0
    motor:
        id: 5
        init: 512
        min: 0
        max: 1023

sfr04_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sfr04_joint
    joint_speed: 1.0
    motor:
        id: 4
        init: 512
        min: 0
        max: 1023

sfr03_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sfr03_joint
    joint_speed: 1.0
    motor:
        id: 3
        init: 512
        min: 0
        max: 1023        

sfl02_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sfl02_joint
    joint_speed: 1.0
    motor:
        id: 2
        init: 512
        min: 0
        max: 1023

sfl01_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sfl01_joint
    joint_speed: 1.0
    motor:
        id: 1
        init: 512
        min: 0
        max: 1023

sfl00_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sfl00_joint
    joint_speed: 1.0
    motor:
        id: 0
        init: 512
        min: 0
        max: 1023  


sbr11_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sbr11_joint
    joint_speed: 1.0
    motor:
        id: 11
        init: 512
        min: 0
        max: 1023

sbr10_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sbr10_joint
    joint_speed: 1.0
    motor:
        id: 10
        init: 512
        min: 0
        max: 1023

sbr09_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sbr09_joint
    joint_speed: 1.0
    motor:
        id: 9
        init: 512
        min: 0
        max: 1023        

sbl08_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sbl08_joint
    joint_speed: 1.0
    motor:
        id: 8
        init: 512
        min: 0
        max: 1023

sbl07_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sbl07_joint
    joint_speed: 1.0
    motor:
        id: 7
        init: 512
        min: 0
        max: 1023

sbl06_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sbl07_joint
    joint_speed: 1.0
    motor:
        id: 6
        init: 512
        min: 0
        max: 1023  