slf11_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: slf11_joint
    joint_speed: 0.20
    motor:
        id: 2
        init: 512
        min: 316
        max: 708

slf12_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: slf12_joint
    joint_speed: 0.20
    motor:
        id: 6
        init: 512
        min: 316
        max: 708

slf13_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: slf13_joint
    joint_speed: 0.20
    motor:
        id: 10
        init: 512
        min: 316
        max: 708        
